/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package view.spot.finder;

import view.spot.finder.data.models.Element;
import view.spot.finder.data.mesh.Mesh;
import view.spot.finder.out.ElementListPrinter;
import view.spot.finder.data.provider.FileBasedDataProvider;
import view.spot.finder.spotfinder.MeshSpotFinder;
import view.spot.finder.validation.InputValidator;

import java.util.List;

/**
 * This class serves as entry point for the view-spot-finder.
 */
public class App {
    public static void main(String[] args) {
        if(InputValidator.validate(args)) {
            run(args[0], Integer.parseInt(args[1]));
        }
    }

    public static void run(String fileName, int maxSpotViews) {
        String jsonString = FileBasedDataProvider.load(fileName);
        if(jsonString != null) {
            Mesh mesh = Mesh.fromJsonString(jsonString);
            MeshSpotFinder finder = new MeshSpotFinder(mesh);
            List<Element> viewSpotList =  finder.findSpots(maxSpotViews);
            ElementListPrinter.print(viewSpotList);
        }
    }
}
